### PR TITLE
Improve readability of patchmatch.py

### PR DESCRIPTION
**Pull request by johnwlambert**
Improve readability of patchmatch.py by adding type annotations and reformatting file with Python `black`.

### CODE REVIEW

**Review by FangjinhuaWang — COMMENTED** [review]
Hi, John:
Line 144: propagation neighbors generally equals to 8 (in a static pattern, they are eight other pixels in a 3x3 window)
Line 610: shape is (B,1,H,W)
Line 796: Hope you can replace "3D convolution" with "1x1x1 conv", which is just as a MLP. Because "3D convolution" usually refers to the case with a spatial window (e.g. 3x3x3). But we do not use any of this knid of convolution as discussed in our paper (supplementary).

Thanks a lot for your work!

**Comment by johnwlambert** [comment]
Thanks @FangjinhuaWang  -- I've updated it now. Please let me know if that looks better now.

**Review by FangjinhuaWang — APPROVED** [review]

**Comment by FangjinhuaWang** [comment]
Hi, John:

I fix several bugs in your push. For example, torch.Tensor([0]) is on "cpu", and it is a scalar which cannot be broadcasted to a large shape (e.g. similarity_sum=0). 

Hope that you can have a test before pushing the codes. Thanks!

**Comment by johnwlambert** [comment]
@FangjinhuaWang thanks for catching that -- sorry for the issue. We forgot to test on GPU, not just CPU, so looks like there was a device mismatch we didn't account for. Thanks again.

**Pull request merged**
